apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: sample-ace-project
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-BSVCHU
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        image: "us.icr.io/cp4i-gse-poc/sample-ace-project:f569bb199aee9113f908258d9f17c8bfb19fa07e"
    imagePullSecrets:
      - name: ibm-cr-pull-secret
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0.11-r1
